#!/usr/bin/env bash
function all() {
  editor
  locale
  lang
  localtime
  hwclock
  hostname
  dhcp
  wifi
  sudo
}

function install() {
  pacman -S --needed --noconfirm "$@"
}

function nag() {
  echo try again
}

function editor() {
  echo editor?
  select EDITOR in vi vim nano; do
    case $EDITOR in
      vim) install vim ;&
      vi) ;&
      nano) break ;;
      *) nag ;;
    esac
  done
  export EDITOR
}

function locale() {
  [[ -n $EDITOR ]] || editor
  $EDITOR /etc/locale.gen
  locale-gen
}

function lang() {
  local locales=$(egrep -v '^(#.*)?$' /etc/locale.gen | cut -d' ' -f1)
  if [[ -z $locales ]]; then
      locale
      lang
      return
  fi
  while true; do
    echo -n 'locale? '
    read LANG
    for locale in $locales; do
      [[ $LANG = $locale ]] && break
    done
    [[ $LANG = $locale ]] && break
    nag
  done
  echo LANG=$LANG >/etc/locale.conf
  export LANG
}

function localtime() {
  local zone
  while [[ ! -e /usr/share/zoneinfo/$zone ]]; do
    echo -n 'localtime? '
    read zone
  done
  ln -s /usr/share/zoneinfo/$zone /etc/localtime
}

function hwclock() {
  echo hwclock?
  select offset in utc localtime; do
    case $offset in
      utc) ;&
      localtime) hwclock --systohc --$offset
                 break ;;
      *) nag ;;
    esac
  done
}

function hostname() {
  local hostname
  while [[ -z $hostname ]]; do
    echo -n 'hostname? '
    read hostname
  done
  echo $hostname >/etc/hostname
}

function dhcp() {
  systemctl enable dhcpcd
}

function wifi() {
  install iw wpa_supplicant dialog
}

function sudo() {
  install sudo
  perl -i -0 -pe 's/^# (%wheel ALL=\(ALL\))$/\1/' /etc/sudoers
}
