#!/usr/bin/env bash

function default() {
  editor
  locale
  lang
  localtime
  hwclock
  hostname
  dhcp
  wifi
  grub
}

function install() {
  pacman --sync --needed --noconfirm "$@"
}

function yes() {
  local answer
  read answer
  case "$answer" in
    [Yy]|[Yy][Ee][Ss]) return 0 ;;
  esac
  return 1;
}

function nag() {
  sleep 1 # apparent bug in bash select construct
          # causes text to be on same line
          # as menu choice if printed too fast
  echo try again
}

function editor() {
  echo editor?
  select EDITOR in vim vi nano; do
    case $EDITOR in
      vim) install vim ;&
      vi) ;&
      nano) break ;;
      *) nag ;;
    esac
  done
  export EDITOR
}

function locale() {
  [[ -n $EDITOR ]] || editor
  $EDITOR /etc/locale.gen
  locale-gen
}

function lang() {
  local locales=$(egrep -v '^(#.*)?$' /etc/locale.gen | cut -d' ' -f1)
  if [[ -z $locales ]]; then
      locale
      lang
      return
  fi
  echo locale?
  select LANG in $locales; do
    for locale in $locales; do
      [[ $LANG = $locale ]] && break
    done
    [[ $LANG = $locale ]] && break
    nag
  done
  echo LANG=$LANG >/etc/locale.conf
  export LANG
}

function localtime() {
  if [[ ! -e /etc/localtime ]]; then
    local zone
    cd /usr/share/zoneinfo
    while [[ -z $zone || ! -e /usr/share/zoneinfo/$zone ]]; do
      echo -n 'localtime? (tab-tab) '
      read -e zone
    done
    ln -s $PWD/$zone /etc/localtime
    cd - >/dev/null
  fi
}

function hwclock() {
  echo hwclock?
  select offset in utc localtime; do
    case $offset in
      utc) ;&
      localtime) break ;;
      *) nag ;;
    esac
  done
  command hwclock --systohc --$offset
}

function hostname() {
  local hostname
  while [[ -z $hostname ]]; do
    echo -n 'hostname? '
    read hostname
  done
  echo $hostname >/etc/hostname
}

function dhcp() {
  echo -n 'want dhcp? '
  yes && systemctl enable dhcpcd
}

function wifi() {
  echo -n 'want wifi? '
  yes && install iw wpa_supplicant dialog
}

function grub() {
  install grub os-prober
  grub-install --recheck /dev/sda
  grub-mkconfig -o /boot/grub/grub.cfg
}

function help() {
  echo default - everything below
  echo editor - choose \$EDITOR
  echo locale - choose locales then locale-gen
  echo lang - choose LANG from available locales
  echo localtime - link /etc/localtime
  echo hwclock - utc or localtime
  echo hostname - set hostname
  echo dhcp - enables dhcpcd
  echo wifi - installs wifi packages
  echo grub - installs grub with os-prober to /dev/sda
}

case "$1" in
  editor) editor ;;
  locale) locale ;;
  lang) lang ;;
  localtime) localtime ;;
  hwclock) hwclock ;;
  hostname) hostname ;;
  dhcp) dhcp ;;
  wifi) wifi ;;
  grub) grub ;;
  help) help ;;
  *) default ;;
esac
