#!/usr/bin/env bash

function default() {
  editor
  locale
  lang
  localtime
  hwclock
  hostname
  dhcp
  wifi
  grub
  root
  sudo
  adduser
}

function install() {
  pacman --sync --needed --noconfirm "$@"
}

function yes() {
  local answer
  read answer
  case "$answer" in
    [Yy]|[Yy][Ee][Ss]) return 0 ;;
  esac
  return 1;
}

function echo() {
  sleep 1 # apparent bug in virtualbox
          # causes text to be on same line
          # as menu choice if printed too fast
  command echo "$@"
}

function nag() {
  echo try again
}

function editor() {
  echo editor?
  select EDITOR in vim vi nano; do
    case $EDITOR in
      vim) install vim ;&
      vi) ;&
      nano) break ;;
      *) nag ;;
    esac
  done
  export EDITOR
}

function locale() {
  [[ -n $EDITOR ]] || editor
  $EDITOR /etc/locale.gen
  locale-gen
}

function lang() {
  local locales=$(egrep -v '^(#.*)?$' /etc/locale.gen | cut -d' ' -f1)
  if [[ -z $locales ]]; then
      locale
      lang
      return
  fi
  echo locale?
  select LANG in $locales; do
    for locale in $locales; do
      [[ $LANG = $locale ]] && break
    done
    [[ $LANG = $locale ]] && break
    nag
  done
  echo LANG=$LANG >/etc/locale.conf
  export LANG
}

function localtime() {
  if [[ ! -e /etc/localtime ]]; then
    local zone
    cd /usr/share/zoneinfo
    while [[ -z $zone || ! -e /usr/share/zoneinfo/$zone ]]; do
      echo -n 'localtime? (tab-tab) '
      read -e zone
    done
    ln -s $PWD/$zone /etc/localtime
    cd - >/dev/null
  fi
}

function hwclock() {
  echo hwclock?
  select offset in utc localtime; do
    case $offset in
      utc) ;&
      localtime) break ;;
      *) nag ;;
    esac
  done
  command hwclock --systohc --$offset
}

function hostname() {
  local hostname
  while [[ -z $hostname ]]; do
    echo -n 'hostname? '
    read hostname
  done
  echo $hostname >/etc/hostname
}

function dhcp() {
  echo -n 'want dhcp? '
  yes && systemctl enable dhcpcd
}

function wifi() {
  echo -n 'want wifi? '
  yes && install iw wpa_supplicant dialog
}

function grub() {
  local device
  while [[ ! -b $device ]]; do
    echo -n 'what device for grub? '
    read device
  done
  install grub os-prober
  grub-install --recheck $device
  local grubcfg=/boot/grub/grub.cfg
  grub-mkconfig -o $grubcfg
  [[ -e $grubcfg.new ]] && mv $grubcfg{.new,} # apparent bug with os-prober
}

function root() {
  echo for root
  passwd
}

function sudo() {
  perl -i -0 -pe 's/# (%wheel ALL=\(ALL\) ALL)/\1/' /etc/sudoers
}

function adduser() {
  local username
  while [[ -z $username ]]; do
    echo -n 'username? '
    read username
  done
  useradd -m $username
  passwd $username
  chfn $username
  echo -n "want sudo for $username? "
  yes && gpasswd -a $username wheel
  echo -n 'more users? '
  yes && adduser
}

function help() {
  echo default - everything below
  echo editor - choose \$EDITOR
  echo locale - choose locales then locale-gen
  echo lang - choose LANG from available locales
  echo localtime - link /etc/localtime
  echo hwclock - utc or localtime
  echo hostname - set hostname
  echo dhcp - enables dhcpcd
  echo wifi - installs wifi packages
  echo grub - installs grub with os-prober
  echo root - sets root password
  echo sudo - gives wheel group access sudo
  echo adduser - what do you think?
}

if [[ $(type -t "$1") = function ]]; then
  "$1"
else
  default
fi
